version: "3"

services:
  web:
    build: ./docker
    # ./dockerディレクトリのDockerfileを使う
    container_name: php7.4-apache
    # コンテナ名
    ports:
      - 80:80
      # ポート番号→ホスト:コンテナ
    volumes:
      - ./html/:/var/www/html/
      # ホストOSで./htmlにtest.htmlを作ると、コンテナ内の/var/www/webにも、test.htmlが作られる。
      # コンテナ内にデータの永続化するため。キー（ホスト）バリュー（コンテナ）
    depends_on:
      - db
      # dbコンテナができてから、webコンテナを立ち上げる

  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
      TZ: Asia/Tokyo
    ports:
      - 5432:5432
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    restart: always

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    hostname: pgadmin4
    ports:
      - 8888:80
    volumes:
      - ./docker/pgadmin4:/var/lib/pgadmin
    depends_on:
      - db
